---
title: Topic modeling and homology between the spaces of positions and position-takings <!--# or between discourses? anyway, a working title -->
author:   
  - Pierre Benz
  - Radim Hladík
  - Yann Renisio
strip-comments: true
---

<!--# 
R:
- feel free to rewrite anything, i have no attachment to my words (besides, everything is versioned and buried in git history)
- at this point this is more or less just notes from today's discussion
-->


<!--# 
P:
- Here is a first draft for an abstract. Please commit and change everything ;)
-->

Topic modeling is a suite of information retrieval algorithms that has become popular in sociological applications. 
Various techniques covering Bayesian inference, network-based co-wording and deep learning-based embeddings have flourished in recent literature. 
Despite the widespread adoption of topic models for semi-automatic labeling, there is a notable scarcity of studies that approach this method from a sociological perspective. 
As a dimensionality reduction technique, topic modeling assumes that the content of documents can be described by a limited set of topics, or distributions over vocabulary, which are typically interpretable by domain experts. 
Based on this operational definition, studies tend to use topic modeling with a focus on interpreting or discovering particular topics. 
Here, we propose to shift the perspective and argue for a sociological appropriation of the method that would focus on the structure of discourse that surfaces in the latent topic space. 
By highlighting this, often overlooked, feature of topic models, namely the representation of documents as distribution over topics, we aim to emphasize the intrinsically relational character of topic models. 
The framework of the collective book lends itself perfectly to such task, namely to demonstrate the sociological potential of topic models to uncover homological structures.
Thus, we will aim to demonstrate how topic models are useful tools for examining homologies between discursive and social dimensions of fields, or between different discursive spaces, with empirical evidence from the scientific field. 
More broadly, we will emphasize the relationality of topic models, and the way it empowers sociologists to study how different linguistic markets create symbolic values and structure them according to their specific logic.

<!--# 
P:
- These are our brainstorm ideas
-->

Topic modeling is a suite of information retrieval algorithms that has become popular in sociological applications.
As a dimensionality reduction technique, topic modeling assumes that the content of documents can be described by a limited set of topics, or distributions over vocabulary, which are typically interpretable by domain experts.
In our contribution, we want to highlight another, often overlooked, feature of topic models, namely the representation of documents as distributions over topics.
This quality imbues topic models with an intrinsically relational character.
We argue that sociological appropriation of topic models should shift its focus from interpreting or discovering particular topics to the analysis of structure of discourse that surfaces in the latent topic space.
The relationality of topic models empowers sociologists to study how different linguistic markets create symbolic values and structure them according to their specific logic.
Topic models are therefore useful tools for examining homologies between discursive and social dimensions of fields, or between different discursive spaces.
We will demonstrate the sociological potential of topic models to uncover homological structures with examples from the scientific field.
Pierre: I totally agree with what you are saying here.
I wonder if topic modeling has become popular in sociological applications, or if we may rather say that although topic modeling has entered the social sciences for about a decade (typically this special issue in Poetics 2013), its potential in terms of sociological application has remained limited / debated.
Discussion in the literature about the potential use of topic models for sociology (like DiMaggio, 2015) is more about comparing views from information scientists with those from sociologists, rather than an in-depth empirically-informed theoretical look into topic models and their relational properties.
This is where we integrate the discussion,introducing the often overlooked feature of topic models, namely the representation of documents as distributions over topics. 
Here, we emphasize that such approach is key to understanding how documents, hence their authors, combine different topics.
We also stress that the resulting 'map' of documents/topics echoes the distribution of authors' social properties, hence homology between position-takings and positions.
Relational is key here, because it is both an inherent feature of topic modeling and a very property of fields and fields theory.