
abbrev_discs <- function(discipline) {
  discipline_abbr <- tidytable::case_when(
    discipline == "Agricultural biotechnology" ~ "AgriBiotech",
    discipline == "Agriculture, Forestry, and Fisheries" ~ "AgriForeFish",
    discipline == "Animal and Dairy science" ~ "AniDairySci",
    discipline == "Arts (arts, history of arts, performing arts, music)" ~ "Arts",
    discipline == "Basic medicine" ~ "BasicMed",
    discipline == "Biological sciences" ~ "BioSci",
    discipline == "Chemical engineering" ~ "ChemEng",
    discipline == "Chemical sciences" ~ "ChemSci",
    discipline == "Civil engineering" ~ "CivEng",
    discipline == "Clinical medicine" ~ "ClinMed",
    discipline == "Computer and information sciences" ~ "CompInfoSci",
    discipline == "Earth and related environmental sciences" ~ "EarthEnvSci",
    discipline == "Economics and Business" ~ "EconBus",
    discipline == "Education" ~ "Edu",
    discipline == "Electrical eng., Electronic eng., Information eng." ~ "ElectrInfoEng",
    discipline == "Environmental biotechnology" ~ "EnvBiotech",
    discipline == "Environmental engineering" ~ "EnvEng",
    discipline == "Health sciences" ~ "HealthSci",
    discipline == "History and Archaeology" ~ "HistArch",
    discipline == "Industrial biotechnology" ~ "IndustryBiotech",
    discipline == "Languages and Literature" ~ "LangLit",
    discipline == "Law" ~ "Law",
    discipline == "Materials engineering" ~ "MaterialEng",
    discipline == "Mathematics" ~ "Math",
    discipline == "Mechanical engineering" ~ "MechanicalEng",
    discipline == "Media and communications" ~ "MediaComm",
    discipline == "Medical biotechnology" ~ "MedBiotech",
    discipline == "Medical engineering" ~ "MedEng",
    discipline == "Nano-technology" ~ "NanoTech",
    discipline == "Other Humanities and the Arts" ~ "OtherHumArts",
    discipline == "Other agricultural sciences" ~ "OtherAgriSci",
    discipline == "Other engineering and technologies" ~ "OtherEngTech",
    discipline == "Other medical sciences" ~ "OtherMedSci",
    discipline == "Other natural sciences" ~ "OtherNatSci",
    discipline == "Other social sciences" ~ "OtherSocSci",
    discipline == "Philosophy, Ethics and Religion" ~ "PhilEthRel",
    discipline == "Physical sciences" ~ "PhysicalSci",
    discipline == "Political science" ~ "PoliticalSci",
    discipline == "Psychology and cognitive sciences" ~ "PsychCogSci",
    discipline == "Social and economic geography" ~ "SocEcoGeo",
    discipline == "Sociology" ~ "Sociology",
    discipline == "Veterinary science" ~ "VeterinarySci",
    TRUE ~ discipline
  )
}
